version: '3.7'
services:
  mongo:
    container_name: khong_biet_mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./docker_volumes/mongo:/data/db
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=es, s3, ec2, dynamodb, elasticcache, sqs #AWS Services that you want in your localstack
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=abc
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./docker_volumes/s3}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: awslocal kinesis list-streams